# Generated by Django 3.2.8 on 2022-02-05 11:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0015_rename_swimming_pooll_hotel_swimming_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bookingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('no_person', models.IntegerField()),
                ('bookprice', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
