# Generated by Django 3.2.8 on 2022-02-05 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_bookinguser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
