# Generated by Django 3.2.8 on 2022-01-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bookinguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookingUser',
        ),
    ]
