# Generated by Django 3.2.8 on 2022-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bookinguser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguser',
            name='pay_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
