# Generated by Django 3.2.8 on 2022-01-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_hotel_hotel_price'),
        ('myapp', '0004_delete_bookinguser'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('no_person', models.IntegerField()),
                ('bookprice', models.IntegerField(default=0)),
                ('hname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.hotel')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
