# Generated by Django 3.2.8 on 2022-03-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bookinguser_cancel_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguser',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
