# Generated by Django 3.2.8 on 2021-12-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.FileField(default='avtar.png', upload_to='Profile pic'),
        ),
    ]
