# Generated by Django 3.2.8 on 2021-12-30 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_auto_20211230_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('hotel_adderss', models.TextField()),
                ('hotel_rooms', models.IntegerField()),
                ('hotel_mobile', models.CharField(max_length=20)),
                ('hotel_wifi', models.BooleanField()),
                ('hotel_photos', models.FileField(blank=True, null=True, upload_to='hotel pic')),
                ('add_details', models.TextField()),
                ('hotel_acroom', models.BooleanField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.user')),
            ],
        ),
    ]
