# Generated by Django 3.2.8 on 2022-01-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_hotel_hotel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_acroom',
            field=models.CharField(max_length=30),
        ),
    ]
