# Generated by Django 3.2.8 on 2022-01-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_alter_hotel_hotel_acroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_price',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
