# Generated by Django 3.2.8 on 2022-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_alter_hotel_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='bed_room',
            field=models.FileField(blank=True, null=True, upload_to='bed room'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='beds_room',
            field=models.FileField(blank=True, null=True, upload_to='bed room'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_frontview',
            field=models.FileField(blank=True, null=True, upload_to='bed room'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='swmming_phool',
            field=models.FileField(blank=True, null=True, upload_to='bed room'),
        ),
    ]
