# Generated by Django 3.2.8 on 2022-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0011_auto_20220127_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='beds_room',
            field=models.FileField(blank=True, null=True, upload_to='beds room'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_frontview',
            field=models.FileField(blank=True, null=True, upload_to='hotel frontview'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='swmming_phool',
            field=models.FileField(blank=True, null=True, upload_to='swmming phool'),
        ),
    ]
