# Generated by Django 3.2.8 on 2022-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0015_rename_swimming_pooll_hotel_swimming_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_wifi',
            field=models.CharField(max_length=20),
        ),
    ]
