# Generated by Django 3.2.8 on 2022-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0016_alter_hotel_hotel_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_wifi',
            field=models.BooleanField(),
        ),
    ]
