# Generated by Django 3.2.8 on 2022-02-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0017_alter_hotel_hotel_wifi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_adderss',
            new_name='hotel_address',
        ),
    ]
